// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayObservation(r []Observation, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeObservation(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayObservationWrapper struct {
	Target *[]Observation
}

func (_ ArrayObservationWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayObservationWrapper) Finalize()                        {}
func (_ ArrayObservationWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayObservationWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Observation, 0, s)
	}
}
func (r ArrayObservationWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayObservationWrapper) AppendArray() types.Field {
	var v Observation
	v = NewObservation()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
