// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayIdentityViolation(r []IdentityViolation, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeIdentityViolation(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayIdentityViolationWrapper struct {
	Target *[]IdentityViolation
}

func (_ ArrayIdentityViolationWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayIdentityViolationWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayIdentityViolationWrapper) Finalize()        {}
func (_ ArrayIdentityViolationWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayIdentityViolationWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]IdentityViolation, 0, s)
	}
}
func (r ArrayIdentityViolationWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayIdentityViolationWrapper) AppendArray() types.Field {
	var v IdentityViolation
	v = NewIdentityViolation()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
