// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayTrait(r []Trait, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeTrait(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayTraitWrapper struct {
	Target *[]Trait
}

func (_ ArrayTraitWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayTraitWrapper) Finalize()                        {}
func (_ ArrayTraitWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayTraitWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Trait, 0, s)
	}
}
func (r ArrayTraitWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayTraitWrapper) AppendArray() types.Field {
	var v Trait
	v = NewTrait()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
