// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayConversationSummary(r []ConversationSummary, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeConversationSummary(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayConversationSummaryWrapper struct {
	Target *[]ConversationSummary
}

func (_ ArrayConversationSummaryWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayConversationSummaryWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayConversationSummaryWrapper) Finalize()        {}
func (_ ArrayConversationSummaryWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayConversationSummaryWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]ConversationSummary, 0, s)
	}
}
func (r ArrayConversationSummaryWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayConversationSummaryWrapper) AppendArray() types.Field {
	var v ConversationSummary
	v = NewConversationSummary()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
