// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayIdentifier(r []Identifier, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeIdentifier(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayIdentifierWrapper struct {
	Target *[]Identifier
}

func (_ ArrayIdentifierWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayIdentifierWrapper) Finalize()                        {}
func (_ ArrayIdentifierWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayIdentifierWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Identifier, 0, s)
	}
}
func (r ArrayIdentifierWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayIdentifierWrapper) AppendArray() types.Field {
	var v Identifier
	v = NewIdentifier()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
