// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayMerge(r []Merge, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeMerge(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayMergeWrapper struct {
	Target *[]Merge
}

func (_ ArrayMergeWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayMergeWrapper) Finalize()                        {}
func (_ ArrayMergeWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayMergeWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Merge, 0, s)
	}
}
func (r ArrayMergeWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayMergeWrapper) AppendArray() types.Field {
	var v Merge
	v = NewMerge()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
