// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// indicates whether a profile has conflicting data          - RESOLVED indicates that a profile has no conflicts.  An event marked as this may have             accumulated traits or identifiers  which need to be consumed immediately,  since those values             will *not* remain accumulated or specially marked  on subsequent events.          - CONFLICT indicates that the profile has at least one conflict; trait changes and             identifiers will be "accumulated" during this time,  and marked as TraitCause and             IdentityCause.
type ConflictStatus int32

const (
	ConflictStatusUNKNOWN  ConflictStatus = 0
	ConflictStatusRESOLVED ConflictStatus = 1
	ConflictStatusCONFLICT ConflictStatus = 2
)

func (e ConflictStatus) String() string {
	switch e {
	case ConflictStatusUNKNOWN:
		return "UNKNOWN"
	case ConflictStatusRESOLVED:
		return "RESOLVED"
	case ConflictStatusCONFLICT:
		return "CONFLICT"
	}
	return "unknown"
}

func writeConflictStatus(r ConflictStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewConflictStatusValue(raw string) (r ConflictStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return ConflictStatusUNKNOWN, nil
	case "RESOLVED":
		return ConflictStatusRESOLVED, nil
	case "CONFLICT":
		return ConflictStatusCONFLICT, nil
	}

	return ConflictStatusUNKNOWN, nil

}

func (b ConflictStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ConflictStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewConflictStatusValue(stringVal)
	*b = val
	return err
}

type ConflictStatusWrapper struct {
	Target *ConflictStatus
}

func (b ConflictStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ConflictStatusWrapper) SetInt(v int32) {
	*(b.Target) = ConflictStatus(v)
}

func (b ConflictStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ConflictStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ConflictStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ConflictStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ConflictStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ConflictStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ConflictStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ConflictStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ConflictStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ConflictStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ConflictStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ConflictStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ConflictStatusWrapper) Finalize() {}
