// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ConversationSummaryCause int32

const (
	ConversationSummaryCauseUNKNOWN      ConversationSummaryCause = 0
	ConversationSummaryCauseUNREFERENCED ConversationSummaryCause = 1
	ConversationSummaryCauseNOOP         ConversationSummaryCause = 2
	ConversationSummaryCauseUPDATED      ConversationSummaryCause = 3
	ConversationSummaryCauseMERGED       ConversationSummaryCause = 4
	ConversationSummaryCauseEVICTED      ConversationSummaryCause = 5
)

func (e ConversationSummaryCause) String() string {
	switch e {
	case ConversationSummaryCauseUNKNOWN:
		return "UNKNOWN"
	case ConversationSummaryCauseUNREFERENCED:
		return "UNREFERENCED"
	case ConversationSummaryCauseNOOP:
		return "NOOP"
	case ConversationSummaryCauseUPDATED:
		return "UPDATED"
	case ConversationSummaryCauseMERGED:
		return "MERGED"
	case ConversationSummaryCauseEVICTED:
		return "EVICTED"
	}
	return "unknown"
}

func writeConversationSummaryCause(r ConversationSummaryCause, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewConversationSummaryCauseValue(raw string) (r ConversationSummaryCause, err error) {
	switch raw {
	case "UNKNOWN":
		return ConversationSummaryCauseUNKNOWN, nil
	case "UNREFERENCED":
		return ConversationSummaryCauseUNREFERENCED, nil
	case "NOOP":
		return ConversationSummaryCauseNOOP, nil
	case "UPDATED":
		return ConversationSummaryCauseUPDATED, nil
	case "MERGED":
		return ConversationSummaryCauseMERGED, nil
	case "EVICTED":
		return ConversationSummaryCauseEVICTED, nil
	}

	return ConversationSummaryCauseUNKNOWN, nil

}

func (b ConversationSummaryCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ConversationSummaryCause) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewConversationSummaryCauseValue(stringVal)
	*b = val
	return err
}

type ConversationSummaryCauseWrapper struct {
	Target *ConversationSummaryCause
}

func (b ConversationSummaryCauseWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ConversationSummaryCauseWrapper) SetInt(v int32) {
	*(b.Target) = ConversationSummaryCause(v)
}

func (b ConversationSummaryCauseWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ConversationSummaryCauseWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ConversationSummaryCauseWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ConversationSummaryCauseWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ConversationSummaryCauseWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ConversationSummaryCauseWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ConversationSummaryCauseWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ConversationSummaryCauseWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ConversationSummaryCauseWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ConversationSummaryCauseWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ConversationSummaryCauseWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ConversationSummaryCauseWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ConversationSummaryCauseWrapper) Finalize() {}
