// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// structured metadata about an event that may not accompany every event, but is common enough to be written into the contract
type ConversationSummaryMetadata struct {
	ConversationId string `json:"conversationId"`

	CommunicationId string `json:"communicationId"`

	OperatorId string `json:"operatorId"`
}

const ConversationSummaryMetadataAvroCRC64Fingerprint = "7D\xc7%(7\x92^"

func NewConversationSummaryMetadata() ConversationSummaryMetadata {
	r := ConversationSummaryMetadata{}
	return r
}

func DeserializeConversationSummaryMetadata(r io.Reader) (ConversationSummaryMetadata, error) {
	t := NewConversationSummaryMetadata()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeConversationSummaryMetadataFromSchema(r io.Reader, schema string) (ConversationSummaryMetadata, error) {
	t := NewConversationSummaryMetadata()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeConversationSummaryMetadata(r ConversationSummaryMetadata, w io.Writer) error {
	var err error
	err = vm.WriteString(r.ConversationId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CommunicationId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.OperatorId, w)
	if err != nil {
		return err
	}
	return err
}

func (r ConversationSummaryMetadata) Serialize(w io.Writer) error {
	return writeConversationSummaryMetadata(r, w)
}

func (r ConversationSummaryMetadata) Schema() string {
	return "{\"doc\":\"structured metadata about an event that may not accompany every event, but is common enough\\nto be written into the contract\",\"fields\":[{\"name\":\"conversationId\",\"type\":\"string\"},{\"name\":\"communicationId\",\"type\":\"string\"},{\"name\":\"operatorId\",\"type\":\"string\"}],\"name\":\"twilio.memora.patchstream.v1.ConversationSummaryMetadata\",\"type\":\"record\"}"
}

func (r ConversationSummaryMetadata) SchemaName() string {
	return "twilio.memora.patchstream.v1.ConversationSummaryMetadata"
}

func (_ ConversationSummaryMetadata) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetString(v string)   { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ConversationSummaryMetadata) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.ConversationId}

		return w

	case 1:
		w := types.String{Target: &r.CommunicationId}

		return w

	case 2:
		w := types.String{Target: &r.OperatorId}

		return w

	}
	panic("Unknown field index")
}

func (r *ConversationSummaryMetadata) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ConversationSummaryMetadata) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ConversationSummaryMetadata) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ConversationSummaryMetadata) AppendArray() types.Field { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) HintSize(int)             { panic("Unsupported operation") }
func (_ ConversationSummaryMetadata) Finalize()                {}

func (_ ConversationSummaryMetadata) AvroCRC64Fingerprint() []byte {
	return []byte(ConversationSummaryMetadataAvroCRC64Fingerprint)
}

func (r ConversationSummaryMetadata) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["conversationId"], err = json.Marshal(r.ConversationId)
	if err != nil {
		return nil, err
	}
	output["communicationId"], err = json.Marshal(r.CommunicationId)
	if err != nil {
		return nil, err
	}
	output["operatorId"], err = json.Marshal(r.OperatorId)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ConversationSummaryMetadata) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["conversationId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ConversationId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for conversationId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["communicationId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CommunicationId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for communicationId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["operatorId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OperatorId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for operatorId")
	}
	return nil
}
