// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ConversationSummaryStatus int32

const (
	ConversationSummaryStatusUNKNOWN   ConversationSummaryStatus = 0
	ConversationSummaryStatusUNCHANGED ConversationSummaryStatus = 1
	ConversationSummaryStatusADDED     ConversationSummaryStatus = 2
	ConversationSummaryStatusCHANGED   ConversationSummaryStatus = 3
	ConversationSummaryStatusDELETED   ConversationSummaryStatus = 4
)

func (e ConversationSummaryStatus) String() string {
	switch e {
	case ConversationSummaryStatusUNKNOWN:
		return "UNKNOWN"
	case ConversationSummaryStatusUNCHANGED:
		return "UNCHANGED"
	case ConversationSummaryStatusADDED:
		return "ADDED"
	case ConversationSummaryStatusCHANGED:
		return "CHANGED"
	case ConversationSummaryStatusDELETED:
		return "DELETED"
	}
	return "unknown"
}

func writeConversationSummaryStatus(r ConversationSummaryStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewConversationSummaryStatusValue(raw string) (r ConversationSummaryStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return ConversationSummaryStatusUNKNOWN, nil
	case "UNCHANGED":
		return ConversationSummaryStatusUNCHANGED, nil
	case "ADDED":
		return ConversationSummaryStatusADDED, nil
	case "CHANGED":
		return ConversationSummaryStatusCHANGED, nil
	case "DELETED":
		return ConversationSummaryStatusDELETED, nil
	}

	return ConversationSummaryStatusUNKNOWN, nil

}

func (b ConversationSummaryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ConversationSummaryStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewConversationSummaryStatusValue(stringVal)
	*b = val
	return err
}

type ConversationSummaryStatusWrapper struct {
	Target *ConversationSummaryStatus
}

func (b ConversationSummaryStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ConversationSummaryStatusWrapper) SetInt(v int32) {
	*(b.Target) = ConversationSummaryStatus(v)
}

func (b ConversationSummaryStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ConversationSummaryStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ConversationSummaryStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ConversationSummaryStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ConversationSummaryStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ConversationSummaryStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ConversationSummaryStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ConversationSummaryStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ConversationSummaryStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ConversationSummaryStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ConversationSummaryStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ConversationSummaryStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ConversationSummaryStatusWrapper) Finalize() {}
