// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewIdentifierWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewIdentifier()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type IdentifierReader struct {
	r io.Reader
	p *vm.Program
}

func NewIdentifierReader(r io.Reader) (*IdentifierReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewIdentifier()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &IdentifierReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r IdentifierReader) Read() (Identifier, error) {
	t := NewIdentifier()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
