// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// indication that a potential identifier failed to be promoted from a trait, usually due to a defined limit being reached
type IdentityViolation struct {
	IdType string `json:"idType"`

	Id string `json:"id"`

	Type string `json:"type"`

	Metadata map[string]string `json:"metadata"`

	ProfileIdsAttempted []string `json:"profileIdsAttempted"`
}

const IdentityViolationAvroCRC64Fingerprint = "z*\x03ds\x19\a\x02"

func NewIdentityViolation() IdentityViolation {
	r := IdentityViolation{}
	r.Metadata = make(map[string]string)

	r.ProfileIdsAttempted = make([]string, 0)

	r.ProfileIdsAttempted = make([]string, 0)

	return r
}

func DeserializeIdentityViolation(r io.Reader) (IdentityViolation, error) {
	t := NewIdentityViolation()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeIdentityViolationFromSchema(r io.Reader, schema string) (IdentityViolation, error) {
	t := NewIdentityViolation()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeIdentityViolation(r IdentityViolation, w io.Writer) error {
	var err error
	err = vm.WriteString(r.IdType, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Type, w)
	if err != nil {
		return err
	}
	err = writeMapString(r.Metadata, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.ProfileIdsAttempted, w)
	if err != nil {
		return err
	}
	return err
}

func (r IdentityViolation) Serialize(w io.Writer) error {
	return writeIdentityViolation(r, w)
}

func (r IdentityViolation) Schema() string {
	return "{\"doc\":\"indication that a potential identifier failed to be promoted from a trait, usually due to a\\ndefined limit being reached\",\"fields\":[{\"name\":\"idType\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"default\":[],\"name\":\"profileIdsAttempted\",\"type\":{\"items\":\"string\",\"type\":\"array\"}}],\"name\":\"twilio.memora.patchstream.v1.IdentityViolation\",\"type\":\"record\"}"
}

func (r IdentityViolation) SchemaName() string {
	return "twilio.memora.patchstream.v1.IdentityViolation"
}

func (_ IdentityViolation) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ IdentityViolation) SetInt(v int32)       { panic("Unsupported operation") }
func (_ IdentityViolation) SetLong(v int64)      { panic("Unsupported operation") }
func (_ IdentityViolation) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ IdentityViolation) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ IdentityViolation) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ IdentityViolation) SetString(v string)   { panic("Unsupported operation") }
func (_ IdentityViolation) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *IdentityViolation) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.IdType}

		return w

	case 1:
		w := types.String{Target: &r.Id}

		return w

	case 2:
		w := types.String{Target: &r.Type}

		return w

	case 3:
		r.Metadata = make(map[string]string)

		w := MapStringWrapper{Target: &r.Metadata}

		return &w

	case 4:
		r.ProfileIdsAttempted = make([]string, 0)

		w := ArrayStringWrapper{Target: &r.ProfileIdsAttempted}

		return w

	}
	panic("Unknown field index")
}

func (r *IdentityViolation) SetDefault(i int) {
	switch i {
	case 4:
		r.ProfileIdsAttempted = make([]string, 0)

		return
	}
	panic("Unknown field index")
}

func (r *IdentityViolation) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ IdentityViolation) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ IdentityViolation) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ IdentityViolation) HintSize(int)                     { panic("Unsupported operation") }
func (_ IdentityViolation) Finalize()                        {}

func (_ IdentityViolation) AvroCRC64Fingerprint() []byte {
	return []byte(IdentityViolationAvroCRC64Fingerprint)
}

func (r IdentityViolation) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["idType"], err = json.Marshal(r.IdType)
	if err != nil {
		return nil, err
	}
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["type"], err = json.Marshal(r.Type)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	output["profileIdsAttempted"], err = json.Marshal(r.ProfileIdsAttempted)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *IdentityViolation) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["idType"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdType); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for idType")
	}
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	val = func() json.RawMessage {
		if v, ok := fields["profileIdsAttempted"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ProfileIdsAttempted); err != nil {
			return err
		}
	} else {
		r.ProfileIdsAttempted = make([]string, 0)

		r.ProfileIdsAttempted = make([]string, 0)

	}
	return nil
}
