// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// qualifies IdentifierStatus values with further information.         Some consumers may be able to ignore IdentifierCause         if IdentifierStatus is sufficient to fulfill their needs.          - UNREFERENCED only occurs with Status=UNCHANGED,             and indicates that this identifier was not referred to             in the event causing this patch to be emitted.          - NOOP only occurs with IdentifierStatusUnchanged,             and indicates that a identifier was referenced in original event,             but had no effect because the profile already had the identifier.          - ACCUMULATED only occurs with Status=UNCHANGED,             and represents any identifiers which have been added             at or since the time of the profile becoming conflicted,             until the point of profile resolution;             identifiers added in the same event as a resolution             would just have an IdentiferStatusAdded value.          - UPDATED indicates that the identifier was simply added             or otherwise changed, but not as part of a merge.          - MERGED only occurs with Status=Added,             and represents an identifier which is was inherited             from a subsumed ProfileId.             This takes precedence over Cause=Noop.
type IdentifierCause int32

const (
	IdentifierCauseUNKNOWN      IdentifierCause = 0
	IdentifierCauseUNREFERENCED IdentifierCause = 1
	IdentifierCauseNOOP         IdentifierCause = 2
	IdentifierCauseACCUMULATED  IdentifierCause = 3
	IdentifierCauseUPDATED      IdentifierCause = 4
	IdentifierCauseMERGED       IdentifierCause = 5
)

func (e IdentifierCause) String() string {
	switch e {
	case IdentifierCauseUNKNOWN:
		return "UNKNOWN"
	case IdentifierCauseUNREFERENCED:
		return "UNREFERENCED"
	case IdentifierCauseNOOP:
		return "NOOP"
	case IdentifierCauseACCUMULATED:
		return "ACCUMULATED"
	case IdentifierCauseUPDATED:
		return "UPDATED"
	case IdentifierCauseMERGED:
		return "MERGED"
	}
	return "unknown"
}

func writeIdentifierCause(r IdentifierCause, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewIdentifierCauseValue(raw string) (r IdentifierCause, err error) {
	switch raw {
	case "UNKNOWN":
		return IdentifierCauseUNKNOWN, nil
	case "UNREFERENCED":
		return IdentifierCauseUNREFERENCED, nil
	case "NOOP":
		return IdentifierCauseNOOP, nil
	case "ACCUMULATED":
		return IdentifierCauseACCUMULATED, nil
	case "UPDATED":
		return IdentifierCauseUPDATED, nil
	case "MERGED":
		return IdentifierCauseMERGED, nil
	}

	return IdentifierCauseUNKNOWN, nil

}

func (b IdentifierCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *IdentifierCause) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewIdentifierCauseValue(stringVal)
	*b = val
	return err
}

type IdentifierCauseWrapper struct {
	Target *IdentifierCause
}

func (b IdentifierCauseWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b IdentifierCauseWrapper) SetInt(v int32) {
	*(b.Target) = IdentifierCause(v)
}

func (b IdentifierCauseWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b IdentifierCauseWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b IdentifierCauseWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b IdentifierCauseWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b IdentifierCauseWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b IdentifierCauseWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b IdentifierCauseWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b IdentifierCauseWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b IdentifierCauseWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b IdentifierCauseWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b IdentifierCauseWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b IdentifierCauseWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b IdentifierCauseWrapper) Finalize() {}
