// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// indicates the high-level effect of the event on a identifier.         Consumers should use IdentifierStatus to determine         how to interpret identifier data in the patch stream,         and IdentifierCause to determine why a change happened.          - UNCHANGED indicates that this identifier is provided as a "snapshot" value,             but was not changed due to this event. The occurrence of events which merely             mention an identifier will not cause the identifier to be considered "changed".          - ADDED This identifier was added to this profile due to this event, for any of the             following reasons:              1. A direct identifier addition to the profile,                in which case the identifier likely has not been observed before.             2. A merge, in which case this identifier is new to this ProfileID,                but not new to the profile as a whole.          - DELETED this identifier was deleted from this profile due to this event
type IdentifierStatus int32

const (
	IdentifierStatusUNKNOWN   IdentifierStatus = 0
	IdentifierStatusUNCHANGED IdentifierStatus = 1
	IdentifierStatusADDED     IdentifierStatus = 2
	IdentifierStatusDELETED   IdentifierStatus = 3
)

func (e IdentifierStatus) String() string {
	switch e {
	case IdentifierStatusUNKNOWN:
		return "UNKNOWN"
	case IdentifierStatusUNCHANGED:
		return "UNCHANGED"
	case IdentifierStatusADDED:
		return "ADDED"
	case IdentifierStatusDELETED:
		return "DELETED"
	}
	return "unknown"
}

func writeIdentifierStatus(r IdentifierStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewIdentifierStatusValue(raw string) (r IdentifierStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return IdentifierStatusUNKNOWN, nil
	case "UNCHANGED":
		return IdentifierStatusUNCHANGED, nil
	case "ADDED":
		return IdentifierStatusADDED, nil
	case "DELETED":
		return IdentifierStatusDELETED, nil
	}

	return IdentifierStatusUNKNOWN, nil

}

func (b IdentifierStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *IdentifierStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewIdentifierStatusValue(stringVal)
	*b = val
	return err
}

type IdentifierStatusWrapper struct {
	Target *IdentifierStatus
}

func (b IdentifierStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b IdentifierStatusWrapper) SetInt(v int32) {
	*(b.Target) = IdentifierStatus(v)
}

func (b IdentifierStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b IdentifierStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b IdentifierStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b IdentifierStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b IdentifierStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b IdentifierStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b IdentifierStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b IdentifierStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b IdentifierStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b IdentifierStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b IdentifierStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b IdentifierStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b IdentifierStatusWrapper) Finalize() {}
