// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapUnionIntLongString(r map[string]UnionIntLongString, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeUnionIntLongString(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapUnionIntLongStringWrapper struct {
	Target *map[string]UnionIntLongString
	keys   []string
	values []UnionIntLongString
}

func (_ *MapUnionIntLongStringWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapUnionIntLongStringWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapUnionIntLongStringWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]UnionIntLongString, 0, s)
	}
}

func (r *MapUnionIntLongStringWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapUnionIntLongStringWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapUnionIntLongStringWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v UnionIntLongString
	v = NewUnionIntLongString()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapUnionIntLongStringWrapper) AppendArray() types.Field { panic("Unsupported operation") }
