// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Merge struct {
	Status MergeStatus `json:"status"`

	FromProfileId string `json:"fromProfileId"`

	CreatedAt int64 `json:"createdAt"`
}

const MergeAvroCRC64Fingerprint = "\xddo\xba\x15L;\xc6\x1f"

func NewMerge() Merge {
	r := Merge{}
	return r
}

func DeserializeMerge(r io.Reader) (Merge, error) {
	t := NewMerge()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeMergeFromSchema(r io.Reader, schema string) (Merge, error) {
	t := NewMerge()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeMerge(r Merge, w io.Writer) error {
	var err error
	err = writeMergeStatus(r.Status, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FromProfileId, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.CreatedAt, w)
	if err != nil {
		return err
	}
	return err
}

func (r Merge) Serialize(w io.Writer) error {
	return writeMerge(r, w)
}

func (r Merge) Schema() string {
	return "{\"fields\":[{\"name\":\"status\",\"type\":{\"default\":\"UNKNOWN\",\"doc\":\"- UNCHANGED indicates that this fromProfileID\\n           was was already associated with the canonical ProfileID,\\n           and thus was not impacted by the current event whatsoever.\\n\\n      - ADDED indicates that this fromProfileID was canonical for\\n           its own profile immediately prior to this event,\\n           but is now no longer canonical, having merged into ProfileID\\n           as part of a merge pertaining to the current event.\",\"name\":\"MergeStatus\",\"symbols\":[\"UNKNOWN\",\"UNCHANGED\",\"ADDED\"],\"type\":\"enum\"}},{\"name\":\"fromProfileId\",\"type\":\"string\"},{\"name\":\"createdAt\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}}],\"name\":\"twilio.memora.patchstream.v1.Merge\",\"type\":\"record\"}"
}

func (r Merge) SchemaName() string {
	return "twilio.memora.patchstream.v1.Merge"
}

func (_ Merge) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Merge) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Merge) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Merge) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Merge) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Merge) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Merge) SetString(v string)   { panic("Unsupported operation") }
func (_ Merge) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Merge) Get(i int) types.Field {
	switch i {
	case 0:
		w := MergeStatusWrapper{Target: &r.Status}

		return w

	case 1:
		w := types.String{Target: &r.FromProfileId}

		return w

	case 2:
		w := types.Long{Target: &r.CreatedAt}

		return w

	}
	panic("Unknown field index")
}

func (r *Merge) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Merge) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Merge) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Merge) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Merge) HintSize(int)                     { panic("Unsupported operation") }
func (_ Merge) Finalize()                        {}

func (_ Merge) AvroCRC64Fingerprint() []byte {
	return []byte(MergeAvroCRC64Fingerprint)
}

func (r Merge) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["status"], err = json.Marshal(r.Status)
	if err != nil {
		return nil, err
	}
	output["fromProfileId"], err = json.Marshal(r.FromProfileId)
	if err != nil {
		return nil, err
	}
	output["createdAt"], err = json.Marshal(r.CreatedAt)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Merge) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["status"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Status); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for status")
	}
	val = func() json.RawMessage {
		if v, ok := fields["fromProfileId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FromProfileId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for fromProfileId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["createdAt"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CreatedAt); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for createdAt")
	}
	return nil
}
