// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// - UNCHANGED indicates that this fromProfileID            was was already associated with the canonical ProfileID,            and thus was not impacted by the current event whatsoever.        - ADDED indicates that this fromProfileID was canonical for            its own profile immediately prior to this event,            but is now no longer canonical, having merged into ProfileID            as part of a merge pertaining to the current event.
type MergeStatus int32

const (
	MergeStatusUNKNOWN   MergeStatus = 0
	MergeStatusUNCHANGED MergeStatus = 1
	MergeStatusADDED     MergeStatus = 2
)

func (e MergeStatus) String() string {
	switch e {
	case MergeStatusUNKNOWN:
		return "UNKNOWN"
	case MergeStatusUNCHANGED:
		return "UNCHANGED"
	case MergeStatusADDED:
		return "ADDED"
	}
	return "unknown"
}

func writeMergeStatus(r MergeStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewMergeStatusValue(raw string) (r MergeStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return MergeStatusUNKNOWN, nil
	case "UNCHANGED":
		return MergeStatusUNCHANGED, nil
	case "ADDED":
		return MergeStatusADDED, nil
	}

	return MergeStatusUNKNOWN, nil

}

func (b MergeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *MergeStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewMergeStatusValue(stringVal)
	*b = val
	return err
}

type MergeStatusWrapper struct {
	Target *MergeStatus
}

func (b MergeStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b MergeStatusWrapper) SetInt(v int32) {
	*(b.Target) = MergeStatus(v)
}

func (b MergeStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b MergeStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b MergeStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b MergeStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b MergeStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b MergeStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b MergeStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b MergeStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b MergeStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b MergeStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b MergeStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b MergeStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b MergeStatusWrapper) Finalize() {}
