// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ObservationConfidence int32

const (
	ObservationConfidenceUNKNOWN ObservationConfidence = 0
	ObservationConfidenceLOW     ObservationConfidence = 1
	ObservationConfidenceMEDIUM  ObservationConfidence = 2
	ObservationConfidenceHIGH    ObservationConfidence = 3
)

func (e ObservationConfidence) String() string {
	switch e {
	case ObservationConfidenceUNKNOWN:
		return "UNKNOWN"
	case ObservationConfidenceLOW:
		return "LOW"
	case ObservationConfidenceMEDIUM:
		return "MEDIUM"
	case ObservationConfidenceHIGH:
		return "HIGH"
	}
	return "unknown"
}

func writeObservationConfidence(r ObservationConfidence, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewObservationConfidenceValue(raw string) (r ObservationConfidence, err error) {
	switch raw {
	case "UNKNOWN":
		return ObservationConfidenceUNKNOWN, nil
	case "LOW":
		return ObservationConfidenceLOW, nil
	case "MEDIUM":
		return ObservationConfidenceMEDIUM, nil
	case "HIGH":
		return ObservationConfidenceHIGH, nil
	}

	return ObservationConfidenceUNKNOWN, nil

}

func (b ObservationConfidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ObservationConfidence) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewObservationConfidenceValue(stringVal)
	*b = val
	return err
}

type ObservationConfidenceWrapper struct {
	Target *ObservationConfidence
}

func (b ObservationConfidenceWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ObservationConfidenceWrapper) SetInt(v int32) {
	*(b.Target) = ObservationConfidence(v)
}

func (b ObservationConfidenceWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ObservationConfidenceWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ObservationConfidenceWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ObservationConfidenceWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ObservationConfidenceWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ObservationConfidenceWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ObservationConfidenceWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ObservationConfidenceWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ObservationConfidenceWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ObservationConfidenceWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ObservationConfidenceWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ObservationConfidenceWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ObservationConfidenceWrapper) Finalize() {}
