// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ObservationStatus int32

const (
	ObservationStatusUNKNOWN   ObservationStatus = 0
	ObservationStatusUNCHANGED ObservationStatus = 1
	ObservationStatusADDED     ObservationStatus = 2
	ObservationStatusCHANGED   ObservationStatus = 3
	ObservationStatusDELETED   ObservationStatus = 4
)

func (e ObservationStatus) String() string {
	switch e {
	case ObservationStatusUNKNOWN:
		return "UNKNOWN"
	case ObservationStatusUNCHANGED:
		return "UNCHANGED"
	case ObservationStatusADDED:
		return "ADDED"
	case ObservationStatusCHANGED:
		return "CHANGED"
	case ObservationStatusDELETED:
		return "DELETED"
	}
	return "unknown"
}

func writeObservationStatus(r ObservationStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewObservationStatusValue(raw string) (r ObservationStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return ObservationStatusUNKNOWN, nil
	case "UNCHANGED":
		return ObservationStatusUNCHANGED, nil
	case "ADDED":
		return ObservationStatusADDED, nil
	case "CHANGED":
		return ObservationStatusCHANGED, nil
	case "DELETED":
		return ObservationStatusDELETED, nil
	}

	return ObservationStatusUNKNOWN, nil

}

func (b ObservationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ObservationStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewObservationStatusValue(stringVal)
	*b = val
	return err
}

type ObservationStatusWrapper struct {
	Target *ObservationStatus
}

func (b ObservationStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ObservationStatusWrapper) SetInt(v int32) {
	*(b.Target) = ObservationStatus(v)
}

func (b ObservationStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ObservationStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ObservationStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ObservationStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ObservationStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ObservationStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ObservationStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ObservationStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ObservationStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ObservationStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ObservationStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ObservationStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ObservationStatusWrapper) Finalize() {}
