// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// structured metadata about an event that may not accompany every event, but is common enough to be written into the contract
type ObservationMetadata struct {
	Confidence ObservationConfidence `json:"confidence"`

	Reason string `json:"reason"`

	ConversationIds []string `json:"conversationIds"`

	CommunicationId string `json:"communicationId"`

	OperatorId string `json:"operatorId"`
}

const ObservationMetadataAvroCRC64Fingerprint = "M\x7f\x8b3c\xab\xe4b"

func NewObservationMetadata() ObservationMetadata {
	r := ObservationMetadata{}
	r.ConversationIds = make([]string, 0)

	return r
}

func DeserializeObservationMetadata(r io.Reader) (ObservationMetadata, error) {
	t := NewObservationMetadata()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeObservationMetadataFromSchema(r io.Reader, schema string) (ObservationMetadata, error) {
	t := NewObservationMetadata()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeObservationMetadata(r ObservationMetadata, w io.Writer) error {
	var err error
	err = writeObservationConfidence(r.Confidence, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Reason, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.ConversationIds, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CommunicationId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.OperatorId, w)
	if err != nil {
		return err
	}
	return err
}

func (r ObservationMetadata) Serialize(w io.Writer) error {
	return writeObservationMetadata(r, w)
}

func (r ObservationMetadata) Schema() string {
	return "{\"doc\":\"structured metadata about an event that may not accompany every event, but is common enough\\nto be written into the contract\",\"fields\":[{\"name\":\"confidence\",\"type\":{\"default\":\"UNKNOWN\",\"name\":\"ObservationConfidence\",\"symbols\":[\"UNKNOWN\",\"LOW\",\"MEDIUM\",\"HIGH\"],\"type\":\"enum\"}},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"conversationIds\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"communicationId\",\"type\":\"string\"},{\"name\":\"operatorId\",\"type\":\"string\"}],\"name\":\"twilio.memora.patchstream.v1.ObservationMetadata\",\"type\":\"record\"}"
}

func (r ObservationMetadata) SchemaName() string {
	return "twilio.memora.patchstream.v1.ObservationMetadata"
}

func (_ ObservationMetadata) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ObservationMetadata) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ObservationMetadata) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ObservationMetadata) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ObservationMetadata) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ObservationMetadata) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ObservationMetadata) SetString(v string)   { panic("Unsupported operation") }
func (_ ObservationMetadata) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ObservationMetadata) Get(i int) types.Field {
	switch i {
	case 0:
		w := ObservationConfidenceWrapper{Target: &r.Confidence}

		return w

	case 1:
		w := types.String{Target: &r.Reason}

		return w

	case 2:
		r.ConversationIds = make([]string, 0)

		w := ArrayStringWrapper{Target: &r.ConversationIds}

		return w

	case 3:
		w := types.String{Target: &r.CommunicationId}

		return w

	case 4:
		w := types.String{Target: &r.OperatorId}

		return w

	}
	panic("Unknown field index")
}

func (r *ObservationMetadata) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ObservationMetadata) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ObservationMetadata) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ObservationMetadata) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ObservationMetadata) HintSize(int)                     { panic("Unsupported operation") }
func (_ ObservationMetadata) Finalize()                        {}

func (_ ObservationMetadata) AvroCRC64Fingerprint() []byte {
	return []byte(ObservationMetadataAvroCRC64Fingerprint)
}

func (r ObservationMetadata) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["confidence"], err = json.Marshal(r.Confidence)
	if err != nil {
		return nil, err
	}
	output["reason"], err = json.Marshal(r.Reason)
	if err != nil {
		return nil, err
	}
	output["conversationIds"], err = json.Marshal(r.ConversationIds)
	if err != nil {
		return nil, err
	}
	output["communicationId"], err = json.Marshal(r.CommunicationId)
	if err != nil {
		return nil, err
	}
	output["operatorId"], err = json.Marshal(r.OperatorId)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ObservationMetadata) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["confidence"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Confidence); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for confidence")
	}
	val = func() json.RawMessage {
		if v, ok := fields["reason"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Reason); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for reason")
	}
	val = func() json.RawMessage {
		if v, ok := fields["conversationIds"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ConversationIds); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for conversationIds")
	}
	val = func() json.RawMessage {
		if v, ok := fields["communicationId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CommunicationId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for communicationId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["operatorId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OperatorId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for operatorId")
	}
	return nil
}
