// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ObservationCause int32

const (
	ObservationCauseUNKNOWN      ObservationCause = 0
	ObservationCauseUNREFERENCED ObservationCause = 1
	ObservationCauseNOOP         ObservationCause = 2
	ObservationCauseUPDATED      ObservationCause = 3
	ObservationCauseMERGED       ObservationCause = 4
	ObservationCauseEVICTED      ObservationCause = 5
)

func (e ObservationCause) String() string {
	switch e {
	case ObservationCauseUNKNOWN:
		return "UNKNOWN"
	case ObservationCauseUNREFERENCED:
		return "UNREFERENCED"
	case ObservationCauseNOOP:
		return "NOOP"
	case ObservationCauseUPDATED:
		return "UPDATED"
	case ObservationCauseMERGED:
		return "MERGED"
	case ObservationCauseEVICTED:
		return "EVICTED"
	}
	return "unknown"
}

func writeObservationCause(r ObservationCause, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewObservationCauseValue(raw string) (r ObservationCause, err error) {
	switch raw {
	case "UNKNOWN":
		return ObservationCauseUNKNOWN, nil
	case "UNREFERENCED":
		return ObservationCauseUNREFERENCED, nil
	case "NOOP":
		return ObservationCauseNOOP, nil
	case "UPDATED":
		return ObservationCauseUPDATED, nil
	case "MERGED":
		return ObservationCauseMERGED, nil
	case "EVICTED":
		return ObservationCauseEVICTED, nil
	}

	return ObservationCauseUNKNOWN, nil

}

func (b ObservationCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ObservationCause) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewObservationCauseValue(stringVal)
	*b = val
	return err
}

type ObservationCauseWrapper struct {
	Target *ObservationCause
}

func (b ObservationCauseWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ObservationCauseWrapper) SetInt(v int32) {
	*(b.Target) = ObservationCause(v)
}

func (b ObservationCauseWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ObservationCauseWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ObservationCauseWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ObservationCauseWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ObservationCauseWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ObservationCauseWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ObservationCauseWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ObservationCauseWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ObservationCauseWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ObservationCauseWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ObservationCauseWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ObservationCauseWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ObservationCauseWrapper) Finalize() {}
