// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewProfileConversationSummaryPatchWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewProfileConversationSummaryPatch()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type ProfileConversationSummaryPatchReader struct {
	r io.Reader
	p *vm.Program
}

func NewProfileConversationSummaryPatchReader(r io.Reader) (*ProfileConversationSummaryPatchReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewProfileConversationSummaryPatch()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ProfileConversationSummaryPatchReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r ProfileConversationSummaryPatchReader) Read() (ProfileConversationSummaryPatch, error) {
	t := NewProfileConversationSummaryPatch()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
