// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewProfileTraitPatchWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewProfileTraitPatch()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type ProfileTraitPatchReader struct {
	r io.Reader
	p *vm.Program
}

func NewProfileTraitPatchReader(r io.Reader) (*ProfileTraitPatchReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewProfileTraitPatch()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ProfileTraitPatchReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r ProfileTraitPatchReader) Read() (ProfileTraitPatch, error) {
	t := NewProfileTraitPatch()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
