// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// describes the outcome of the event         - NORMAL This event does not have any special signifiers. As with many other EventSummary values,             there may be identifier or trait updates.        - CREATED This is the first event pertaining to this profile, and resulted in the creation of the            profile. Consumers which don't need to distinguish between creates and updates may treat this            the same as summary=NORMAL.        - MERGED indicates that one or more other profiles has been superseded by this ProfileID. Consumers            which do not need to be merge-aware can treat this the same as EventSummaryNormal. A merge may            introduce conflicts for some traits: these conflicts can be safely ignored by most consumers.        - TOMBSTONED is the counterpart to summary=MERGED, but applies to a ProfileID which is being            superseded. Consumers which do not need to specially handle the tombstone process as part of a            merge can treat this the same as SUMMARY_DELETED. This is a terminal state: no events will            happen for this profile after this event        - DELETED This indicates that the profile, and all associated resources, should be deleted rapidly            due to a privacy request, profile corruption, or a company ceasing to be a customer.        - SIGNALED indicates that the event was synthesized for an internal Twilio flow, and does not            directly represent any customer-visible state change.        - REEMIT Nothing about the profile has changed as part of this message, but it is being used to            rehydrate downstream systems, either due to corruption or a change in control plane            configuration.        - FIXUP PDS-sourced data repair, restoring data to a state that it should have been in previous,            but for some reason was not
type Summary int32

const (
	SummaryUNKNOWN    Summary = 0
	SummaryNORMAL     Summary = 1
	SummaryCREATED    Summary = 2
	SummaryMERGED     Summary = 3
	SummaryTOMBSTONED Summary = 4
	SummaryDELETED    Summary = 5
	SummarySIGNALED   Summary = 6
	SummaryREEMIT     Summary = 7
	SummaryFIXUP      Summary = 8
)

func (e Summary) String() string {
	switch e {
	case SummaryUNKNOWN:
		return "UNKNOWN"
	case SummaryNORMAL:
		return "NORMAL"
	case SummaryCREATED:
		return "CREATED"
	case SummaryMERGED:
		return "MERGED"
	case SummaryTOMBSTONED:
		return "TOMBSTONED"
	case SummaryDELETED:
		return "DELETED"
	case SummarySIGNALED:
		return "SIGNALED"
	case SummaryREEMIT:
		return "REEMIT"
	case SummaryFIXUP:
		return "FIXUP"
	}
	return "unknown"
}

func writeSummary(r Summary, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewSummaryValue(raw string) (r Summary, err error) {
	switch raw {
	case "UNKNOWN":
		return SummaryUNKNOWN, nil
	case "NORMAL":
		return SummaryNORMAL, nil
	case "CREATED":
		return SummaryCREATED, nil
	case "MERGED":
		return SummaryMERGED, nil
	case "TOMBSTONED":
		return SummaryTOMBSTONED, nil
	case "DELETED":
		return SummaryDELETED, nil
	case "SIGNALED":
		return SummarySIGNALED, nil
	case "REEMIT":
		return SummaryREEMIT, nil
	case "FIXUP":
		return SummaryFIXUP, nil
	}

	return SummaryUNKNOWN, nil

}

func (b Summary) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *Summary) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewSummaryValue(stringVal)
	*b = val
	return err
}

type SummaryWrapper struct {
	Target *Summary
}

func (b SummaryWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b SummaryWrapper) SetInt(v int32) {
	*(b.Target) = Summary(v)
}

func (b SummaryWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b SummaryWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b SummaryWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b SummaryWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b SummaryWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b SummaryWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b SummaryWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b SummaryWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b SummaryWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b SummaryWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b SummaryWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b SummaryWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b SummaryWrapper) Finalize() {}
