// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// indicates the high-level effect of the event on a trait.         Consumers should use TraitStatus to determine         how to interpret trait data in the patch stream,         and TraitCause to determine why a change happened.          - UNCHANGED indicates that this trait is provided as a "snapshot" value,            but was not changed as part of this event.          - CHANGED This trait was updated due to this event.          - CONFLICT indicates that this trait has conflicting values            which could not be immediately resolved, usually but not            always as part of a merge.             Patch consumers which must be conflict-aware            should accumulate and reconcile trait records marked as            Status=CONFLICT.             Patch consumers which do not need to be conflict-aware            may ignore trait records marked as Status=CONFLICT,            and instead only consume the trailing            Status=UNCHANGED trait record.
type TraitStatus int32

const (
	TraitStatusUNKNOWN   TraitStatus = 0
	TraitStatusUNCHANGED TraitStatus = 1
	TraitStatusCHANGED   TraitStatus = 2
	TraitStatusCONFLICT  TraitStatus = 3
	TraitStatusDELETED   TraitStatus = 4
)

func (e TraitStatus) String() string {
	switch e {
	case TraitStatusUNKNOWN:
		return "UNKNOWN"
	case TraitStatusUNCHANGED:
		return "UNCHANGED"
	case TraitStatusCHANGED:
		return "CHANGED"
	case TraitStatusCONFLICT:
		return "CONFLICT"
	case TraitStatusDELETED:
		return "DELETED"
	}
	return "unknown"
}

func writeTraitStatus(r TraitStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewTraitStatusValue(raw string) (r TraitStatus, err error) {
	switch raw {
	case "UNKNOWN":
		return TraitStatusUNKNOWN, nil
	case "UNCHANGED":
		return TraitStatusUNCHANGED, nil
	case "CHANGED":
		return TraitStatusCHANGED, nil
	case "CONFLICT":
		return TraitStatusCONFLICT, nil
	case "DELETED":
		return TraitStatusDELETED, nil
	}

	return TraitStatusUNKNOWN, nil

}

func (b TraitStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *TraitStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewTraitStatusValue(stringVal)
	*b = val
	return err
}

type TraitStatusWrapper struct {
	Target *TraitStatus
}

func (b TraitStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b TraitStatusWrapper) SetInt(v int32) {
	*(b.Target) = TraitStatus(v)
}

func (b TraitStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b TraitStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b TraitStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b TraitStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b TraitStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b TraitStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b TraitStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b TraitStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b TraitStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b TraitStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b TraitStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b TraitStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b TraitStatusWrapper) Finalize() {}
