// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// qualifies TraitStatus values with further information.         Some consumers may be able to ignore TraitCause         if TraitStatus is sufficient to fulfill their needs.          - UNREFERENCED only occurs with Status=UNCHANGED,            and indicates that this trait was not referred to            in the original event.          - NOOP only occurs with Status=UNCHANGED,            and indicates that a trait was referenced in original event,            but had no effect because the profile already had the same value,            or absence of a value, for that trait.          - ACCUMULATED only occurs with            Status=UNCHANGED and Status=CONFLICT,            and represents any traits which have been changed            at or since the time of the profile becoming conflicted,            until the point of profile resolution;            traits changed in the same event as the resolution itself            will merely be listed as Status=CHANGED.          - UPDATED indicates that the trait was simply updated,            not as part of a merge, and may have been expressed            as an add, update, or delete.          - MERGED only occurs with Status=CHANGED and Status=CONFLICT,            and represents a trait which is changed            from the perspective of the new canonical ProfileID (this profile),            but inherited unchanged from a subsumed ProfileID.
type TraitCause int32

const (
	TraitCauseUNKNOWN      TraitCause = 0
	TraitCauseUNREFERENCED TraitCause = 1
	TraitCauseNOOP         TraitCause = 2
	TraitCauseACCUMULATED  TraitCause = 3
	TraitCauseUPDATED      TraitCause = 4
	TraitCauseMERGED       TraitCause = 5
)

func (e TraitCause) String() string {
	switch e {
	case TraitCauseUNKNOWN:
		return "UNKNOWN"
	case TraitCauseUNREFERENCED:
		return "UNREFERENCED"
	case TraitCauseNOOP:
		return "NOOP"
	case TraitCauseACCUMULATED:
		return "ACCUMULATED"
	case TraitCauseUPDATED:
		return "UPDATED"
	case TraitCauseMERGED:
		return "MERGED"
	}
	return "unknown"
}

func writeTraitCause(r TraitCause, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewTraitCauseValue(raw string) (r TraitCause, err error) {
	switch raw {
	case "UNKNOWN":
		return TraitCauseUNKNOWN, nil
	case "UNREFERENCED":
		return TraitCauseUNREFERENCED, nil
	case "NOOP":
		return TraitCauseNOOP, nil
	case "ACCUMULATED":
		return TraitCauseACCUMULATED, nil
	case "UPDATED":
		return TraitCauseUPDATED, nil
	case "MERGED":
		return TraitCauseMERGED, nil
	}

	return TraitCauseUNKNOWN, nil

}

func (b TraitCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *TraitCause) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewTraitCauseValue(stringVal)
	*b = val
	return err
}

type TraitCauseWrapper struct {
	Target *TraitCause
}

func (b TraitCauseWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b TraitCauseWrapper) SetInt(v int32) {
	*(b.Target) = TraitCause(v)
}

func (b TraitCauseWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b TraitCauseWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b TraitCauseWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b TraitCauseWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b TraitCauseWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b TraitCauseWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b TraitCauseWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b TraitCauseWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b TraitCauseWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b TraitCauseWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b TraitCauseWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b TraitCauseWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b TraitCauseWrapper) Finalize() {}
