// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionIntLongStringBoolDoubleFloatNullTypeEnum int

const (
	UnionIntLongStringBoolDoubleFloatNullTypeEnumInt UnionIntLongStringBoolDoubleFloatNullTypeEnum = 0

	UnionIntLongStringBoolDoubleFloatNullTypeEnumLong UnionIntLongStringBoolDoubleFloatNullTypeEnum = 1

	UnionIntLongStringBoolDoubleFloatNullTypeEnumString UnionIntLongStringBoolDoubleFloatNullTypeEnum = 2

	UnionIntLongStringBoolDoubleFloatNullTypeEnumBool UnionIntLongStringBoolDoubleFloatNullTypeEnum = 3

	UnionIntLongStringBoolDoubleFloatNullTypeEnumDouble UnionIntLongStringBoolDoubleFloatNullTypeEnum = 4

	UnionIntLongStringBoolDoubleFloatNullTypeEnumFloat UnionIntLongStringBoolDoubleFloatNullTypeEnum = 5
)

type UnionIntLongStringBoolDoubleFloatNull struct {
	Int       int32
	Long      int64
	String    string
	Bool      bool
	Double    float64
	Float     float32
	Null      *types.NullVal
	UnionType UnionIntLongStringBoolDoubleFloatNullTypeEnum
}

func writeUnionIntLongStringBoolDoubleFloatNull(r *UnionIntLongStringBoolDoubleFloatNull, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(6, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumInt:
		return vm.WriteInt(r.Int, w)
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumLong:
		return vm.WriteLong(r.Long, w)
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumString:
		return vm.WriteString(r.String, w)
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumBool:
		return vm.WriteBool(r.Bool, w)
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumDouble:
		return vm.WriteDouble(r.Double, w)
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumFloat:
		return vm.WriteFloat(r.Float, w)
	}
	return fmt.Errorf("invalid value for *UnionIntLongStringBoolDoubleFloatNull")
}

func NewUnionIntLongStringBoolDoubleFloatNull() *UnionIntLongStringBoolDoubleFloatNull {
	return &UnionIntLongStringBoolDoubleFloatNull{}
}

func (r *UnionIntLongStringBoolDoubleFloatNull) Serialize(w io.Writer) error {
	return writeUnionIntLongStringBoolDoubleFloatNull(r, w)
}

func DeserializeUnionIntLongStringBoolDoubleFloatNull(r io.Reader) (*UnionIntLongStringBoolDoubleFloatNull, error) {
	t := NewUnionIntLongStringBoolDoubleFloatNull()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionIntLongStringBoolDoubleFloatNullFromSchema(r io.Reader, schema string) (*UnionIntLongStringBoolDoubleFloatNull, error) {
	t := NewUnionIntLongStringBoolDoubleFloatNull()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionIntLongStringBoolDoubleFloatNull) Schema() string {
	return "[\"int\",\"long\",\"string\",\"boolean\",\"double\",\"float\",\"null\"]"
}

func (_ *UnionIntLongStringBoolDoubleFloatNull) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionIntLongStringBoolDoubleFloatNull) SetLong(v int64) {

	r.UnionType = (UnionIntLongStringBoolDoubleFloatNullTypeEnum)(v)
}

func (r *UnionIntLongStringBoolDoubleFloatNull) Get(i int) types.Field {

	switch i {
	case 0:
		return &types.Int{Target: (&r.Int)}
	case 1:
		return &types.Long{Target: (&r.Long)}
	case 2:
		return &types.String{Target: (&r.String)}
	case 3:
		return &types.Boolean{Target: (&r.Bool)}
	case 4:
		return &types.Double{Target: (&r.Double)}
	case 5:
		return &types.Float{Target: (&r.Float)}
	case 6:
		return r.Null
	}
	panic("Unknown field index")
}
func (_ *UnionIntLongStringBoolDoubleFloatNull) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionIntLongStringBoolDoubleFloatNull) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionIntLongStringBoolDoubleFloatNull) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionIntLongStringBoolDoubleFloatNull) Finalize() {}

func (r *UnionIntLongStringBoolDoubleFloatNull) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumInt:
		return json.Marshal(map[string]interface{}{"int": r.Int})
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumLong:
		return json.Marshal(map[string]interface{}{"long": r.Long})
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumBool:
		return json.Marshal(map[string]interface{}{"boolean": r.Bool})
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumDouble:
		return json.Marshal(map[string]interface{}{"double": r.Double})
	case UnionIntLongStringBoolDoubleFloatNullTypeEnumFloat:
		return json.Marshal(map[string]interface{}{"float": r.Float})
	}
	return nil, fmt.Errorf("invalid value for *UnionIntLongStringBoolDoubleFloatNull")
}

func (r *UnionIntLongStringBoolDoubleFloatNull) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["int"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Int)
	}
	if value, ok := fields["long"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Long)
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.String)
	}
	if value, ok := fields["boolean"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.Bool)
	}
	if value, ok := fields["double"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.Double)
	}
	if value, ok := fields["float"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.Float)
	}
	return fmt.Errorf("invalid value for *UnionIntLongStringBoolDoubleFloatNull")
}
