// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     ProfileObservationPatch.avsc
 *     ProfileTraitPatch.avsc
 *     ProfileIdentifierPatch.avsc
 *     ProfileConversationSummaryPatch.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionIntLongStringTypeEnum int

const (
	UnionIntLongStringTypeEnumInt UnionIntLongStringTypeEnum = 0

	UnionIntLongStringTypeEnumLong UnionIntLongStringTypeEnum = 1

	UnionIntLongStringTypeEnumString UnionIntLongStringTypeEnum = 2
)

type UnionIntLongString struct {
	Int       int32
	Long      int64
	String    string
	UnionType UnionIntLongStringTypeEnum
}

func writeUnionIntLongString(r UnionIntLongString, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionIntLongStringTypeEnumInt:
		return vm.WriteInt(r.Int, w)
	case UnionIntLongStringTypeEnumLong:
		return vm.WriteLong(r.Long, w)
	case UnionIntLongStringTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for UnionIntLongString")
}

func NewUnionIntLongString() UnionIntLongString {
	return UnionIntLongString{}
}

func (r UnionIntLongString) Serialize(w io.Writer) error {
	return writeUnionIntLongString(r, w)
}

func DeserializeUnionIntLongString(r io.Reader) (UnionIntLongString, error) {
	t := NewUnionIntLongString()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionIntLongStringFromSchema(r io.Reader, schema string) (UnionIntLongString, error) {
	t := NewUnionIntLongString()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r UnionIntLongString) Schema() string {
	return "[\"int\",\"long\",\"string\"]"
}

func (_ UnionIntLongString) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ UnionIntLongString) SetInt(v int32)      { panic("Unsupported operation") }
func (_ UnionIntLongString) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ UnionIntLongString) SetDouble(v float64) { panic("Unsupported operation") }
func (_ UnionIntLongString) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ UnionIntLongString) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionIntLongString) SetLong(v int64) {

	r.UnionType = (UnionIntLongStringTypeEnum)(v)
}

func (r *UnionIntLongString) Get(i int) types.Field {

	switch i {
	case 0:
		return &types.Int{Target: (&r.Int)}
	case 1:
		return &types.Long{Target: (&r.Long)}
	case 2:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ UnionIntLongString) NullField(i int)                  { panic("Unsupported operation") }
func (_ UnionIntLongString) HintSize(i int)                   { panic("Unsupported operation") }
func (_ UnionIntLongString) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ UnionIntLongString) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ UnionIntLongString) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ UnionIntLongString) Finalize()                        {}

func (r UnionIntLongString) MarshalJSON() ([]byte, error) {

	switch r.UnionType {
	case UnionIntLongStringTypeEnumInt:
		return json.Marshal(map[string]interface{}{"int": r.Int})
	case UnionIntLongStringTypeEnumLong:
		return json.Marshal(map[string]interface{}{"long": r.Long})
	case UnionIntLongStringTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for UnionIntLongString")
}

func (r *UnionIntLongString) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["int"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Int)
	}
	if value, ok := fields["long"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Long)
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for UnionIntLongString")
}
